name: textlint-check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install textlint and plugins
        run: npm install -g textlint textlint-plugin-latex2e textlint-rule-prh textlint-rule-no-mix-dearu-desumasu

      - name: Run textlint
        run: |
          textlint -f checkstyle thesis.tex content/**/*.tex > textlint-report.xml || \
          (echo "textlint found errors. See textlint-report.xml" && cat textlint-report.xml && exit 1)

      - name: Show lint errors in GitHub Actions logs
        run: cat textlint-report.xml
