name: textlint-check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install textlint and rules
        run: npm install -g textlint textlint-rule-prh textlint-rule-no-mix-dearu-desumasu

      - name: Run textlint
        run: textlint -f checkstyle thesis.tex content/**/*.tex > textlint-report.xml


      - name: Run reviewdog
        uses: reviewdog/action-eslint@v1  # 公式の reviewdog Action
        with:
          reporter: github-pr-check
          level: warning
          filter_mode: file
          fail_on_error: true
          eslint_flags: "textlint-report.xml"
