name: textlint-check

on:
  pull_request:
    types: [opened, synchronize, reopened] # PRがオープンされたとき、同期されたとき、再オープンされたとき

jobs:
  lint:
    runs-on: ubuntu-22.04  # 特定のバージョンを指定
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install textlint and rules
        run: npm install -g textlint textlint-rule-prh textlint-rule-no-mix-dearu-desumasu

      - name: Run textlint with detailed output
        run: textlint -f checkstyle your-thesis.tex | npx reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-check

